"""
handlers.py — Telegram message handlers and main conversation flow.

Responsibilities:
- Receive and sanitize user input
- Orchestrate the full pipeline: rate limit → cache → translate → search → prune → LLM → respond
- Send Photo Messages with Hebrew captions and affiliate links

Clarification loop state lives in context.user_data["clarification"]:
  {
    "original_query": str,   # raw Hebrew query from the user
    "questions":      list[str],  # Hebrew questions generated by the LLM
    "current_idx":    int,   # index of the question currently being asked
    "answers":        list[str],  # answers collected so far (parallel to questions)
  }
"""

import logging

from telegram import Message, Update
from telegram.constants import ParseMode
from telegram.ext import ContextTypes

from affiliate.generator import generate_affiliate_link
from aliexpress.client import AliExpressAPIError, search_aliexpress
from bot.keyboards import CALLBACK_SKIP_CLARIFICATION, skip_clarification_keyboard
from bot.messages import (
    CARD_DIVIDER,
    CLARIFICATION_FOLLOWUP,
    CLARIFICATION_INTRO,
    CLARIFICATION_REFINING,
    CLARIFICATION_SKIPPED,
    ERROR_API_FAILURE,
    ERROR_LLM_FAILURE,
    ERROR_NO_RESULTS,
    RESULT_CARD,
    RESULT_CARD_NO_RATING,
    RESULTS_HEADER,
    SEARCHING_AI,
    SEARCHING_ALIEXPRESS,
    SEARCHING_TRANSLATING,
    SPEC_WARNING,
    WELCOME,
)
from llm.engine import LLMError, evaluate_products, refine_query, should_clarify_query
from utils.translator import TranslationError, translate_to_english

logger = logging.getLogger(__name__)

# Key used to store clarification state in context.user_data.
_CLARIFY_KEY = "clarification"


# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------

def _format_result_card(pick: dict) -> str:
    """Render a single product pick as an HTML-formatted Telegram message card.

    Args:
        pick: A validated product dict from evaluate_products(), containing
              category_label, title, price_usd, rating, reason, and product_url.

    Returns:
        HTML-formatted string for one product card.
    """
    affiliate_url = generate_affiliate_link(pick["product_url"])
    price = f"{pick['price_usd']:.2f}" if pick["price_usd"] is not None else "—"

    # Warning suffix is hardcoded app text — never LLM-generated — so it is safe to render.
    warning = f"\n{SPEC_WARNING}" if pick.get("spec_warning") else ""

    if pick.get("rating"):
        return RESULT_CARD.format(
            label=pick["category_label"],
            title=pick["title"],
            price=price,
            rating=f"{pick['rating']:.1f}",
            reason=pick["reason"],
            link=affiliate_url,
        ) + warning
    return RESULT_CARD_NO_RATING.format(
        label=pick["category_label"],
        title=pick["title"],
        price=price,
        reason=pick["reason"],
        link=affiliate_url,
    ) + warning


# ---------------------------------------------------------------------------
# Core pipeline (shared by all entry points)
# ---------------------------------------------------------------------------

async def _run_search_pipeline(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
    display_query: str,
    english_query: str,
    holding: Message,
) -> None:
    """Run the AliExpress search + LLM evaluation and edit *holding* with results.

    Args:
        update: Incoming Telegram update (used for user_id in logs).
        context: Callback context (unused here, reserved for future rate limiting).
        display_query: Original Hebrew query shown in the results header.
        english_query: Pre-translated English query sent to AliExpress.
        holding: The message to edit with progress updates and the final result.
    """
    user_id = update.effective_user.id

    await holding.edit_text(SEARCHING_ALIEXPRESS)
    try:
        raw = await search_aliexpress(english_query)
    except AliExpressAPIError as exc:
        logger.error("AliExpress API error for user %s: %s", user_id, exc)
        await holding.edit_text(ERROR_API_FAILURE)
        return

    await holding.edit_text(SEARCHING_AI)
    try:
        picks = await evaluate_products(raw, display_query)
    except LLMError as exc:
        logger.error("LLM evaluation failed for user %s: %s", user_id, exc)
        if "No products to evaluate" in str(exc):
            await holding.edit_text(ERROR_NO_RESULTS)
        else:
            await holding.edit_text(ERROR_LLM_FAILURE)
        return

    cards = CARD_DIVIDER.join(_format_result_card(pick) for pick in picks)
    await holding.edit_text(
        RESULTS_HEADER.format(query=display_query) + cards,
        parse_mode=ParseMode.HTML,
    )


# ---------------------------------------------------------------------------
# Clarification loop helpers
# ---------------------------------------------------------------------------

async def _ask_clarification_question(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    """Send the next clarification question with the skip inline keyboard.

    Reads the current state from context.user_data[_CLARIFY_KEY].

    Args:
        update: Incoming Telegram update (message must be present).
        context: Callback context containing user_data state.
    """
    state: dict = context.user_data[_CLARIFY_KEY]
    idx: int = state["current_idx"]
    total: int = len(state["questions"])
    question: str = state["questions"][idx]

    template = CLARIFICATION_INTRO if idx == 0 else CLARIFICATION_FOLLOWUP
    text = template.format(index=idx + 1, total=total, question=question)

    await update.message.reply_text(
        text,
        parse_mode=ParseMode.HTML,
        reply_markup=skip_clarification_keyboard(),
    )


async def _handle_clarification_answer(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    """Handle a text reply while the clarification loop is active.

    Stores the answer, then either asks the next question or runs the
    full search pipeline once all questions are answered.

    Args:
        update: Incoming Telegram update containing the user's answer.
        context: Callback context containing user_data state.
    """
    state: dict = context.user_data[_CLARIFY_KEY]
    answer: str = (update.message.text or "").strip()
    user_id: int = update.effective_user.id

    state["answers"].append(answer)
    state["current_idx"] += 1

    # More questions remaining — ask the next one.
    if state["current_idx"] < len(state["questions"]):
        await _ask_clarification_question(update, context)
        return

    # All questions answered — refine and search.
    del context.user_data[_CLARIFY_KEY]
    logger.info(
        "User %s completed clarification (%d answers). Refining query.",
        user_id, len(state["answers"]),
    )

    holding: Message = await update.message.reply_text(CLARIFICATION_REFINING)

    try:
        english_query = await refine_query(
            state["original_query"],
            state["questions"],
            state["answers"],
        )
    except LLMError as exc:
        logger.warning(
            "Query refinement failed for user %s (%s). Falling back to plain translation.", user_id, exc
        )
        try:
            english_query = await translate_to_english(state["original_query"])
        except TranslationError:
            await holding.edit_text(ERROR_LLM_FAILURE)
            return

    await _run_search_pipeline(
        update, context, state["original_query"], english_query, holding
    )


# ---------------------------------------------------------------------------
# Public handlers registered in main.py
# ---------------------------------------------------------------------------

async def start_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Handle the /start command with a Hebrew welcome message.

    Also clears any in-progress clarification state so /start always resets the bot.

    Args:
        update: Incoming Telegram update.
        context: Callback context from the dispatcher.
    """
    context.user_data.pop(_CLARIFY_KEY, None)
    user = update.effective_user
    logger.info("User %s started the bot.", user.id if user else "unknown")
    await update.message.reply_text(WELCOME)


async def search_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Handle a free-text message — either a clarification answer or a new search query.

    If a clarification loop is active for this user, routes to
    _handle_clarification_answer. Otherwise starts the full pipeline,
    optionally triggering the clarification loop first for broad queries.

    Args:
        update: Incoming Telegram update.
        context: Callback context from the dispatcher.
    """
    user_text: str = (update.message.text or "").strip()
    user_id: int = update.effective_user.id

    if not user_text:
        return

    # --- Route to clarification answer handler if loop is active ---
    if context.user_data.get(_CLARIFY_KEY):
        await _handle_clarification_answer(update, context)
        return

    logger.info("New search from user %s: %r", user_id, user_text)

    # --- Check if the query needs clarification ---
    try:
        clarification = await should_clarify_query(user_text)
    except LLMError as exc:
        logger.warning(
            "Clarification check failed for user %s (%s). Skipping straight to search.", user_id, exc
        )
        clarification = {"needs_clarification": False, "questions": []}

    if clarification.get("needs_clarification") and clarification.get("questions"):
        context.user_data[_CLARIFY_KEY] = {
            "original_query": user_text,
            "questions": clarification["questions"],
            "current_idx": 0,
            "answers": [],
        }
        await _ask_clarification_question(update, context)
        return

    # --- No clarification needed — run the pipeline directly ---
    holding: Message = await update.message.reply_text(SEARCHING_TRANSLATING)
    try:
        english_query = await translate_to_english(user_text)
    except TranslationError as exc:
        logger.error("Translation failed for user %s: %s", user_id, exc)
        await holding.edit_text(ERROR_LLM_FAILURE)
        return

    logger.info("Translated %r → %r for user %s", user_text, english_query, user_id)
    await _run_search_pipeline(update, context, user_text, english_query, holding)


async def skip_callback_handler(
    update: Update, context: ContextTypes.DEFAULT_TYPE
) -> None:
    """Handle the 'skip clarification' inline button press.

    Clears the clarification state and immediately runs the search pipeline
    using the original query (with plain translation), so the user is never stuck.

    Args:
        update: Incoming Telegram update containing the callback query.
        context: Callback context from the dispatcher.
    """
    query = update.callback_query
    await query.answer()  # Acknowledge the button press to Telegram.

    state: dict = context.user_data.pop(_CLARIFY_KEY, {})
    original_query: str = state.get("original_query", "")
    user_id: int = update.effective_user.id

    logger.info("User %s skipped clarification for query %r.", user_id, original_query)

    # Reuse the question message as the holding message (removes the keyboard).
    holding: Message = query.message
    await holding.edit_text(CLARIFICATION_SKIPPED, reply_markup=None)

    if not original_query:
        return

    await holding.edit_text(SEARCHING_TRANSLATING)
    try:
        english_query = await translate_to_english(original_query)
    except TranslationError as exc:
        logger.error("Translation failed for user %s after skip: %s", user_id, exc)
        await holding.edit_text(ERROR_LLM_FAILURE)
        return

    await _run_search_pipeline(update, context, original_query, english_query, holding)
