"""
handlers.py — Telegram message handlers and main conversation flow.

Responsibilities:
- Receive and sanitize user input
- Orchestrate the full pipeline: translate → search → score → select → respond
- Thread SearchPlan from translation through to confidence scoring

Pipeline (Trust-First Scoring):
  1. translate_to_english()        — Hebrew → SearchPlan + strategy
  2. search_aliexpress_multi()     — Brand RATING axes + category VOLUME axis
  3. select_and_rank_products()    — Score all → LLM picks top 3 → Python labels

Clarification loop state lives in context.user_data["clarification"]:
  {
    "original_query": str,    # raw Hebrew query from the user
    "questions":      list[str],  # Hebrew questions generated by the LLM
    "current_idx":    int,    # index of the question currently being asked
    "answers":        list[str],  # answers collected so far (parallel to questions)
  }
"""

import asyncio
import logging

from telegram import Message, Update
from telegram.constants import ParseMode
from telegram.ext import ContextTypes

from aliexpress.client import AliExpressAPIError, search_aliexpress_multi
from bot.keyboards import CALLBACK_SKIP_CLARIFICATION, skip_clarification_keyboard
from bot.messages import (
    CARD_DIVIDER,
    CLARIFICATION_FOLLOWUP,
    CLARIFICATION_INTRO,
    CLARIFICATION_REFINING,
    CLARIFICATION_SKIPPED,
    ERROR_API_FAILURE,
    ERROR_LLM_FAILURE,
    ERROR_NO_RESULTS,
    PRICE_SUSPICIOUS_WARNING,
    RESULT_CARD,
    RESULT_CARD_NO_RATING,
    RESULTS_HEADER,
    SEARCHING_ALIEXPRESS,
    SEARCHING_FILTERING,
    SEARCHING_TRANSLATING,
    SPEC_WARNING,
    WELCOME,
)
from llm.engine import LLMError, RefinementResult, select_and_rank_products, should_clarify_query, refine_query
from utils.translator import SearchPlan, TranslationError, TranslationResult, merge_search_plans, translate_to_english

logger = logging.getLogger(__name__)

# Key used to store clarification state in context.user_data.
_CLARIFY_KEY = "clarification"


# ---------------------------------------------------------------------------
# Formatting helpers
# ---------------------------------------------------------------------------

def _format_result_card(pick: dict) -> str:
    """Render a single product pick as an HTML-formatted Telegram message card.

    Args:
        pick: A validated product dict from select_and_rank_products(), containing
              category_label, title, price_ils, rating, sales, reason,
              product_url, price_suspicious, and spec_warning.

    Returns:
        HTML-formatted string for one product card.
    """
    price = f"{pick['price_ils']:.0f}" if pick["price_ils"] is not None else "—"
    sales = f"{int(pick.get('sales') or 0):,}"

    # Both warning strings are hardcoded app text — never LLM-generated — so safe to render.
    spec_warn  = f"\n{SPEC_WARNING}"              if pick.get("spec_warning")    else ""
    price_warn = f"\n{PRICE_SUSPICIOUS_WARNING}"  if pick.get("price_suspicious") else ""
    warning = spec_warn + price_warn

    if pick.get("rating"):
        return RESULT_CARD.format(
            label=pick["category_label"],
            title=pick["title"],
            price=price,
            rating=f"{pick['rating']:.1f}",
            sales=sales,
            reason=pick["reason"],
            link=pick["product_url"],
        ) + warning
    return RESULT_CARD_NO_RATING.format(
        label=pick["category_label"],
        title=pick["title"],
        price=price,
        sales=sales,
        reason=pick["reason"],
        link=pick["product_url"],
    ) + warning


# ---------------------------------------------------------------------------
# Core pipeline (shared by all entry points)
# ---------------------------------------------------------------------------

async def _run_search_pipeline(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
    display_query: str,
    translation: TranslationResult,
    holding: Message,
) -> None:
    """Run the full Trust-First search → score → select pipeline.

    Uses translation.search_plan for both multi-axis AliExpress search and
    confidence scoring. Edits *holding* in-place with progress and final results.

    Args:
        update:        Incoming Telegram update (user_id used for logging).
        context:       Callback context (reserved for future rate limiting).
        display_query: Original Hebrew query shown in the results header.
        translation:   TranslationResult including SearchPlan and search_strategy.
        holding:       The Telegram message to edit with progress and final output.
    """
    user_id = update.effective_user.id
    plan    = translation.search_plan
    strategy = translation.search_strategy

    # ── Step 1: Multi-axis parallel fetch ─────────────────────────────────────
    await holding.edit_text(SEARCHING_ALIEXPRESS)
    try:
        raw = await search_aliexpress_multi(
            brand_queries=plan.brand_queries,
            category_query=plan.category_query,
        )
    except AliExpressAPIError as exc:
        logger.error("AliExpress API error for user %s: %s", user_id, exc)
        await holding.edit_text(ERROR_API_FAILURE)
        return

    # ── Step 2: Trust-First scoring → LLM selection → Python labels ───────────
    await holding.edit_text(SEARCHING_FILTERING)
    try:
        picks = await select_and_rank_products(raw, display_query, plan, strategy)
    except LLMError as exc:
        logger.error("Product selection failed for user %s: %s", user_id, exc)
        exc_str = str(exc)
        if "No products to evaluate" in exc_str or "No results:" in exc_str:
            await holding.edit_text(ERROR_NO_RESULTS)
        else:
            await holding.edit_text(ERROR_LLM_FAILURE)
        return

    cards = CARD_DIVIDER.join(_format_result_card(pick) for pick in picks)
    await holding.edit_text(
        RESULTS_HEADER.format(query=display_query) + cards,
        parse_mode=ParseMode.HTML,
    )


# ---------------------------------------------------------------------------
# Clarification loop helpers
# ---------------------------------------------------------------------------

async def _ask_clarification_question(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    """Send the next clarification question with the skip inline keyboard.

    Args:
        update: Incoming Telegram update (message must be present).
        context: Callback context containing user_data state.
    """
    state: dict = context.user_data[_CLARIFY_KEY]
    idx:   int  = state["current_idx"]
    total: int  = len(state["questions"])
    question: str = state["questions"][idx]

    template = CLARIFICATION_INTRO if idx == 0 else CLARIFICATION_FOLLOWUP
    text = template.format(index=idx + 1, total=total, question=question)

    await update.message.reply_text(
        text,
        parse_mode=ParseMode.HTML,
        reply_markup=skip_clarification_keyboard(),
    )


async def _handle_clarification_answer(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    """Handle a text reply while the clarification loop is active.

    Stores the answer, then either asks the next question or runs the
    full search pipeline once all questions are answered.

    When all answers are in, fires translate_to_english and refine_query in
    parallel, then merges their SearchPlans before running the pipeline.

    Args:
        update: Incoming Telegram update containing the user's answer.
        context: Callback context containing user_data state.
    """
    state:   dict = context.user_data[_CLARIFY_KEY]
    answer:  str  = (update.message.text or "").strip()
    user_id: int  = update.effective_user.id

    state["answers"].append(answer)
    state["current_idx"] += 1

    # More questions remaining — ask the next one.
    if state["current_idx"] < len(state["questions"]):
        await _ask_clarification_question(update, context)
        return

    # All questions answered — refine and search.
    del context.user_data[_CLARIFY_KEY]
    logger.info(
        "User %s completed clarification (%d answers). Refining search plan.",
        user_id, len(state["answers"]),
    )

    holding: Message = await update.message.reply_text(CLARIFICATION_REFINING)

    # Fire translate and refine in parallel.
    # translate_to_english → base SearchPlan + strategy.
    # refine_query         → refined SearchPlan from clarification answers.
    translate_outcome, refine_outcome = await asyncio.gather(
        translate_to_english(state["original_query"]),
        refine_query(state["original_query"], state["questions"], state["answers"]),
        return_exceptions=True,
    )

    if isinstance(translate_outcome, Exception):
        logger.error("Translation failed for user %s: %s", user_id, translate_outcome)
        await holding.edit_text(ERROR_LLM_FAILURE)
        return

    translation: TranslationResult = translate_outcome

    if isinstance(refine_outcome, Exception):
        logger.warning(
            "Query refinement failed for user %s (%s) — using base search plan.",
            user_id, refine_outcome,
        )
        # Fall through with the translator's search_plan unchanged.
    elif isinstance(refine_outcome, RefinementResult):
        merged_plan = merge_search_plans(translation.search_plan, refine_outcome.search_plan)
        translation = TranslationResult(
            search_plan=merged_plan,
            search_strategy=translation.search_strategy,
        )
        logger.info(
            "Merged search plans for user %s: brands=%d category=%r window=₪%d–₪%d hints=%d",
            user_id,
            len(merged_plan.brand_queries),
            merged_plan.category_query,
            merged_plan.price_window_ils[0],
            merged_plan.price_window_ils[1],
            len(merged_plan.confidence_hints),
        )

    await _run_search_pipeline(update, context, state["original_query"], translation, holding)


# ---------------------------------------------------------------------------
# Public handlers registered in main.py
# ---------------------------------------------------------------------------

async def start_command(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Handle the /start command with a Hebrew welcome message.

    Also clears any in-progress clarification state so /start always resets.

    Args:
        update: Incoming Telegram update.
        context: Callback context from the dispatcher.
    """
    context.user_data.pop(_CLARIFY_KEY, None)
    user = update.effective_user
    logger.info("User %s started the bot.", user.id if user else "unknown")
    await update.message.reply_text(WELCOME)


async def search_handler(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
    """Handle a free-text message — either a clarification answer or a new search query.

    If a clarification loop is active for this user, routes to
    _handle_clarification_answer. Otherwise starts the full pipeline,
    optionally triggering the clarification loop first for broad queries.

    Args:
        update: Incoming Telegram update.
        context: Callback context from the dispatcher.
    """
    user_text: str = (update.message.text or "").strip()
    user_id:   int = update.effective_user.id

    if not user_text:
        return

    # Route to clarification answer handler if loop is active.
    if context.user_data.get(_CLARIFY_KEY):
        await _handle_clarification_answer(update, context)
        return

    logger.info("New search from user %s: %r", user_id, user_text)

    # Check if the query needs clarification.
    try:
        clarification = await should_clarify_query(user_text)
    except LLMError as exc:
        logger.warning(
            "Clarification check failed for user %s (%s) — skipping to search.", user_id, exc
        )
        clarification = {"needs_clarification": False, "questions": []}

    if clarification.get("needs_clarification") and clarification.get("questions"):
        context.user_data[_CLARIFY_KEY] = {
            "original_query": user_text,
            "questions":      clarification["questions"],
            "current_idx":    0,
            "answers":        [],
        }
        await _ask_clarification_question(update, context)
        return

    # No clarification needed — run the pipeline directly.
    holding: Message = await update.message.reply_text(SEARCHING_TRANSLATING)
    try:
        translation = await translate_to_english(user_text)
    except TranslationError as exc:
        logger.error("Translation failed for user %s: %s", user_id, exc)
        await holding.edit_text(ERROR_LLM_FAILURE)
        return

    logger.info(
        "Translated %r → strategy=%s brands=%d category=%r window=₪%d–₪%d hints=%d",
        user_text,
        translation.search_strategy,
        len(translation.search_plan.brand_queries),
        translation.search_plan.category_query,
        translation.search_plan.price_window_ils[0],
        translation.search_plan.price_window_ils[1],
        len(translation.search_plan.confidence_hints),
    )
    await _run_search_pipeline(update, context, user_text, translation, holding)


async def skip_callback_handler(
    update: Update, context: ContextTypes.DEFAULT_TYPE
) -> None:
    """Handle the 'skip clarification' inline button press.

    Clears the clarification state and immediately runs the search pipeline
    using the original query (with plain translation), so the user is never stuck.

    Args:
        update: Incoming Telegram update containing the callback query.
        context: Callback context from the dispatcher.
    """
    query = update.callback_query
    await query.answer()

    state:          dict = context.user_data.pop(_CLARIFY_KEY, {})
    original_query: str  = state.get("original_query", "")
    user_id:        int  = update.effective_user.id

    logger.info("User %s skipped clarification for query %r.", user_id, original_query)

    holding: Message = query.message
    await holding.edit_text(CLARIFICATION_SKIPPED, reply_markup=None)

    if not original_query:
        return

    await holding.edit_text(SEARCHING_TRANSLATING)
    try:
        translation = await translate_to_english(original_query)
    except TranslationError as exc:
        logger.error("Translation failed for user %s after skip: %s", user_id, exc)
        await holding.edit_text(ERROR_LLM_FAILURE)
        return

    await _run_search_pipeline(update, context, original_query, translation, holding)
